In [14]:
import gurobipy as gp
from gurobipy import GRB
import numpy as np

In [15]:
#Q1 solution 1
m = gp.Model('Q1')
y = np.array([2**i for i in range(6)])
x = m.addMVar(shape=(3,6), vtype='B', name="x")
x_total = np.array([gp.quicksum([y[j] * x[i,j] for j in range(6)]) for i in range(3)])
b = m.addMVar(shape = (1,3),vtype=GRB.BINARY, name="b")
bigM = 100000
for i in range(3):
    m.addConstr(x_total[i] <= bigM * b[0,i])
set_cost = gp.quicksum(b[0][j] * np.array([500,400,300])[j] for j in range(3))
profit = gp.quicksum(x_total[i] * np.array([52,30,20])[i] for i in range(3)) - set_cost
m.setObjective(profit, GRB.MAXIMIZE) 
m.addConstr(gp.quicksum(x_total * np.array([2,4,5])) <= 100)
m.addConstr(gp.quicksum(x_total * np.array([1,1,1])) <= 30)
m.addConstr(gp.quicksum(x_total * np.array([10,5,2])) <= 204)

m.optimize()
print()
print('Profit = ' + str(int(m.ObjVal)))
q = [0,0,0]
for i in range(3):
    for j in range(6):
            q[i] += y[j] * m.getVars()[i*6+j].x
print('Gold = ' + str(int(q[0])))
print('Silver = ' + str(int(q[1])))
print('Bronze = ' + str(int(q[2])))

Gurobi Optimizer version 9.5.2 build v9.5.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 6 rows, 21 columns and 75 nonzeros
Model fingerprint: 0xd25a0875
Variable types: 0 continuous, 21 integer (21 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+05]
  Objective range  [2e+01, 2e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+01, 2e+02]
Found heuristic solution: objective -0.0000000
Presolve removed 0 rows and 15 columns
Presolve time: 0.00s
Presolved: 6 rows, 6 columns, 15 nonzeros
Variable types: 0 continuous, 6 integer (3 binary)

Root relaxation: objective 5.604000e+02, 3 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  560.40000    0    4   -0.00000  560.40000      -     -    0s
H    0     0                     212.0000000  560.40000

In [16]:
#Q1 solution 2
m = gp.Model('Q1')
y = np.array([2**i for i in range(6)])
x = m.addMVar(shape=(3,6), vtype='B', name="x")
x_total = np.array([gp.quicksum([y[j] * x[i,j] for j in range(6)]) for i in range(3)])
b = m.addMVar(shape = (1,3),vtype=GRB.BINARY, name="b1")
set_cost = gp.quicksum(b[0][j] * np.array([500,400,300])[j] for j in range(3))
profit = gp.quicksum(x_total[i] * np.array([52,30,20])[i] * b[0,i] for i in range(3)) - set_cost
m.setObjective(profit, GRB.MAXIMIZE) 
m.addConstr(gp.quicksum(x_total * np.array([2,4,5])) <= 100)
m.addConstr(gp.quicksum(x_total * np.array([1,1,1])) <= 30)
m.addConstr(gp.quicksum(x_total * np.array([10,5,2])) <= 204)

m.optimize()
print()
print('Profit = ' + str(int(m.ObjVal)))
q = [0,0,0]
for i in range(3):
    for j in range(6):
            q[i] += y[j] * m.getVars()[i*6+j].x
print('Gold = ' + str(int(q[0])))
print('Silver = ' + str(int(q[1])))
print('Bronze = ' + str(int(q[2])))

Gurobi Optimizer version 9.5.2 build v9.5.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 3 rows, 21 columns and 54 nonzeros
Model fingerprint: 0xcbca7b9f
Model has 18 quadratic objective terms
Variable types: 0 continuous, 21 integer (21 binary)
Coefficient statistics:
  Matrix range     [1e+00, 3e+02]
  Objective range  [3e+02, 5e+02]
  QObjective range [4e+01, 3e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+01, 2e+02]
Found heuristic solution: objective -0.0000000
Presolve removed 0 rows and 4 columns
Presolve time: 0.00s
Presolved: 17 rows, 31 columns, 87 nonzeros
Variable types: 0 continuous, 31 integer (31 binary)

Root relaxation: objective 7.317677e+02, 16 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  731.76774    0    6   -0.00000  731.767

In [17]:
#Q1 solution 3
m = gp.Model('Q1')
y = np.array([2**i for i in range(6)])
x = m.addMVar(shape=(3,6), vtype='B', name="x")
x_total = np.array([gp.quicksum([y[j] * x[i,j] for j in range(6)]) for i in range(3)])
b = m.addMVar(shape = (1,3),vtype=GRB.BINARY, name="b1")
epsilon = 0.5
bigM = 100000
for i in range(1):
    for j in range(3):
        m.addConstr(x_total[j] >= epsilon - bigM * (1-b[i,j]))
        m.addConstr(x_total[j] <= bigM * b[i,j])
set_cost = gp.quicksum(b[0][j] * np.array([500,400,300])[j] for j in range(3))
profit = gp.quicksum(x_total * np.array([52,30,20])) - set_cost
m.setObjective(profit, GRB.MAXIMIZE) 
m.addConstr(gp.quicksum(x_total * np.array([2,4,5])) <= 100)
m.addConstr(gp.quicksum(x_total * np.array([1,1,1])) <= 30)
m.addConstr(gp.quicksum(x_total * np.array([10,5,2])) <= 204)

m.optimize()
print()
print('Profit = ' + str(int(m.ObjVal)))
q = [0,0,0]
for i in range(3):
    for j in range(6):
            q[i] += y[j] * m.getVars()[i*6+j].x
print('Gold = ' + str(int(q[0])))
print('Silver = ' + str(int(q[1])))
print('Bronze = ' + str(int(q[2])))

Gurobi Optimizer version 9.5.2 build v9.5.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 9 rows, 21 columns and 96 nonzeros
Model fingerprint: 0x8b9161de
Variable types: 0 continuous, 21 integer (21 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+05]
  Objective range  [2e+01, 2e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+01, 1e+05]
Found heuristic solution: objective -0.0000000
Presolve removed 0 rows and 3 columns
Presolve time: 0.00s
Presolved: 9 rows, 18 columns, 81 nonzeros
Variable types: 0 continuous, 18 integer (18 binary)
Found heuristic solution: objective 332.0000000

Root relaxation: objective 5.826393e+02, 4 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  582.63925    0    3  332.00000  582.63925  75.5%     -    0s
H    

In [5]:
#Q2 solution 1
m = gp.Model('Q2')
#x1 = m.addVar(vtype=GRB.INTEGER, name="x1")
#x2 = m.addVar(vtype=GRB.INTEGER, name="x2")
x1 = m.addVar(vtype=GRB.CONTINUOUS, name="x1")
x2 = m.addVar(vtype=GRB.CONTINUOUS, name="x2")
m.setObjective(4*x1+5*x2, GRB.MAXIMIZE) 
m.addConstr(x1+4*x2 <= 10)
m.addConstr(3*x1-4*x2 <= 6)
m.addConstr(x1 <= 4)
m.addConstr(x2 <= 4)
m.addConstr(x1 >= 0)
m.addConstr(x2 >= 0)

#m.addConstr(x1 >= 4)
#m.addConstr(x2 <= 1)

m.optimize()
print()
for v in m.getVars():
    print('%s %g' % (v.VarName, v.X))

print('Obj: %g' % m.ObjVal)

Gurobi Optimizer version 9.5.2 build v9.5.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 6 rows, 2 columns and 8 nonzeros
Model fingerprint: 0xdf466f55
Coefficient statistics:
  Matrix range     [1e+00, 4e+00]
  Objective range  [4e+00, 5e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e+00, 1e+01]
Presolve removed 6 rows and 2 columns
Presolve time: 0.04s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    2.3500000e+01   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.05 seconds (0.00 work units)
Optimal objective  2.350000000e+01

x1 4
x2 1.5
Obj: 23.5


In [6]:
#Q4 solution 
m = gp.Model('Q2')

prob = np.array([[0.5,0.6,0.7,0.5],[0.6,0.7,0.8,0.7],[0.8,0.8,0.9,0.9]]).T
cost = np.array([[1,2,1,2],[2,4,3,3],[3,5,4,4]]).T
x = m.addMVar(shape = (4,3),vtype='B', name="x")
#p01 = m.addVar(vtype=GRB.CONTINUOUS, name="p01")
#p23 = m.addVar(vtype=GRB.CONTINUOUS, name="p23")
p = m.addVar(vtype=GRB.CONTINUOUS, lb = 0, ub = 1, name="p")
x_0_m = m.addMVar(shape = (3,3),vtype='B', name="x_0_m")
x_1_m = m.addMVar(shape = (3,3),vtype='B', name="x_1_m")
x_0_1 = m.addMVar(shape = (3,3),vtype='B', name="x_0_1")
x_2_m = m.addMVar(shape = (3,3),vtype='B', name="x_2_m")
x_3_m = m.addMVar(shape = (3,3),vtype='B', name="x_3_m")
x_2_3 = m.addMVar(shape = (3,3),vtype='B', name="x_2_3")

prob_matrix_0_1 = np.ones((3,3))
for i in range(3):
    for j in range(3):
        prob_matrix_0_1[i,j] = prob[0,i] * prob[1,j]
prob_matrix_2_3 = np.ones((3,3))
for i in range(3):
    for j in range(3):
        prob_matrix_2_3[i,j] = prob[2,i] * prob[3,j]
       
# x_0_m = np.zeros((3,3))
# x_1_m = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        m.addConstr(x_0_m[i,j] == x[0,i])
        m.addConstr(x_1_m[i,j] == x[1,j])
for i in range(3):
    for j in range(3):
        m.addConstr(x_0_1[i,j] == x_0_m[i,j] * x_1_m[i,j])
#x_2_m = np.zeros((3,3))
#x_3_m = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        m.addConstr(x_2_m[i,j] == x[2,i])
        m.addConstr(x_3_m[i,j] == x[3,j])
for i in range(3):
    for j in range(3):
        m.addConstr(x_2_3[i,j] == x_2_m[i,j] * x_3_m[i,j])
        
#x_0_1 = np.zeros((3,3), dtype = np.int8)
#for i in range(3):
#    for j in range(3):
#        m.addConstr(x_0_1[i,j] == gp.quicksum(x[0,i] * x[1,j] for j in range(3) for i in range(3)))
#x_2_3 = np.zeros((3,3))
#for i in range(3):
#    for j in range(3):
#        m.addConstr(x_2_3[i,j] == gp.quicksum(x[2,i] * x[3,j] for j in range(3) for i in range(3)))
        
p_0_1 = gp.quicksum(prob_matrix_0_1[i,j] * x_0_1[i,j] for j in range(3) for i in range(3))
p_2_3 = gp.quicksum(prob_matrix_2_3[i,j] * x_2_3[i,j] for j in range(3) for i in range(3))

#p_0_1 = np.ones((3,3))
#for i in range(3):
#    for j in range(3):
#        p_0_1[i,j] = prob_matrix_0_1[0,i] * x_0_1[1,j]
#p_2_3 = np.ones((3,3))
#for i in range(3):
#    for j in range(3):
#        p_2_3[i,j] = prob_matrix_2_3[0,i] * x_2_3[1,j]

        
        
# p01 = gp.quicksum(x[0,j] * prob_matrix_0_1[0,j] for j in range(3))  *

# p = [0,0,0,0]
# for i in range(4):
#    p[i] = gp.quicksum(prob[0,j] * x[0,j] for j in range(3))

totalCost = 0
for i in range(4):
    totalCost += gp.quicksum(cost[i,j] * x[i,j] for j in range(3))

for i in range(4):
    m.addConstr(gp.quicksum(x[i]) == 1)
m.addConstr(totalCost <= 10)

m.addConstr(p == p_0_1 * p_2_3)
#m.addConstr(p01 == p[0] * p[1])
#m.addConstr(p23 == p[2] * p[3])
#m.addConstr(pAll == p01* p23)
m.setObjective(p, GRB.MAXIMIZE) 

m.optimize()
if m.status == GRB.Status.INFEASIBLE:
    m.computeIIS()
    m.write("model1.ilp")
print()
print('Obj: %g' % m.ObjVal)
print()
for v in m.getVars():
    print('%s %g' % (v.VarName, v.X))


Gurobi Optimizer version 9.5.2 build v9.5.2rc0 (win64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 41 rows, 67 columns and 96 nonzeros
Model fingerprint: 0xa93e378c
Model has 19 quadratic constraints
Variable types: 1 continuous, 66 integer (66 binary)
Coefficient statistics:
  Matrix range     [1e+00, 5e+00]
  QMatrix range    [1e-01, 1e+00]
  QLMatrix range   [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+01]
Presolve removed 36 rows and 36 columns
Presolve time: 0.04s
Presolved: 321 rows, 130 columns, 831 nonzeros
Variable types: 1 continuous, 129 integer (129 binary)
Found heuristic solution: objective 0.1050000
Found heuristic solution: objective 0.1680000
Found heuristic solution: objective 0.1960000

Root relaxation: objective 1.000000e+00, 63 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 E

In [7]:
np.array([[0.5,0.6,0.7,0.5],[0.6,0.7,0.8,0.7],[0.8,0.8,0.9,0.9]]).T

array([[0.5, 0.6, 0.8],
       [0.6, 0.7, 0.8],
       [0.7, 0.8, 0.9],
       [0.5, 0.7, 0.9]])

In [8]:
prob_matrix_0_1 = np.ones((3,3))
for i in range(3):
    for j in range(3):
        prob_matrix_0_1[i,j] = prob[0,i] * prob[1,j]


In [9]:
prob_matrix_0_1

array([[0.3 , 0.35, 0.4 ],
       [0.36, 0.42, 0.48],
       [0.48, 0.56, 0.64]])

In [10]:
x = np.array([[0,0,1],[1,0,0],[1,0,0],[0,0,1]])

In [11]:
x_0_m = np.zeros((3,3))
x_1_m = np.zeros((3,3))
x_0_1 = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        x_0_m[i,j] = x[0,i]
        x_1_m[i,j] = x[1,j]
for i in range(3):
    for j in range(3):
        x_0_1[i,j] = x_0_m[i,j] * x_1_m[i,j]
x_0_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [12]:
x_0_m

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [13]:
x_1_m

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])